import { defineConfig } from "tsup";

export default defineConfig({
  entry: ["src/index.ts"],
  format: ["cjs", "esm"],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  shims: true,
  target: "es2020",
  external: [
    "react",
    "react-dom",
    "react-hook-form",
    "@hookform/resolvers",
    "next",
    "next-themes",
    "@radix-ui/react-slot",
    "@radix-ui/react-label",
    "@radix-ui/react-avatar",
    "@radix-ui/react-checkbox",
    "@radix-ui/react-collapsible",
    "@radix-ui/react-dialog",
    "@radix-ui/react-dropdown-menu",
    "@radix-ui/react-popover",
    "@radix-ui/react-progress",
    "@radix-ui/react-select",
    "@radix-ui/react-separator",
    "@radix-ui/react-switch",
    "@radix-ui/react-toggle",
    "@radix-ui/react-tooltip",
    "@tanstack/react-table",
    "lucide-react",
    "recharts",
    "cmdk",
    "react-day-picker",
    "date-fns",
    "sonner",
    "@mikestraczek/cms-core",
  ],
  tsconfig: "./tsconfig.json",
});
