import {
  AlertTriangle,
  ArrowLeft,
  CheckCircle,
  ChevronLeft,
  CreditCard,
  Home,
  Keyboard,
  Laptop,
  LayoutDashboard,
  Loader2,
  Lock,
  LogOut,
  MailIcon,
  Settings,
  UserIcon,
  Users,
  EllipsisVertical,
  PanelLeftOpen,
  PanelLeftClose,
  Building2,
  FileText,
  Table,
  MapPin,
  Bed,
  Receipt,
  Armchair,
  Square,
  Monitor,
  Calendar,
  X,
  FileIcon,
  TreePine,
  Trash,
} from "lucide-react";

export const Icons = {
  user: UserIcon,
  settings: Settings,
  logout: LogOut,
  home: Home,
  dashboard: LayoutDashboard,
  laptop: Laptop,
  billing: CreditCard,
  spinner: Loader2,
  lock: Lock,
  mail: MailIcon,
  warning: AlertTriangle,
  success: CheckCircle,
  back: ArrowLeft,
  chevronLeft: ChevronLeft,
  keyboard: Keyboard,
  users: Users,
  menu: EllipsisVertical,
  panelLeftOpen: PanelLeftOpen,
  panelLeftClose: PanelLeftClose,
  office: Building2,
  fileText: FileText,
  table: Table,
  city: MapPin,
  room: Bed,
  receipt: Receipt,
  desk: Armchair,
  workTable: Square,
  workstation: Monitor,
  payment: CreditCard,
  booking: Calendar,
  x: X,
  file: FileIcon,
  tree: TreePine,
  trash: Trash,
};
